=== AdrianMarque/HtmlPaginaPrincipal/biblioteca.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="biblioteca">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="anime" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="anime">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Nombre" type="xs:string"/>
        <xs:element name="Director" type="xs:string"/>
        <xs:element name="Año" type="xs:string"/>
        <xs:element name="Episodios" type="xs:string"/>
        <xs:element name="Seiyuu" type="xs:string"/>
        <xs:element name="Genero" type="xs:string"/>
        <xs:element name="Sinopsis" type="xs:string"/>
        <xs:element name="Criticas" type="xs:string"/>
        <xs:element name="Finalizado" type="xs:string"/>
        <xs:element name="Trailer" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AdrianMarque/HtmlPaginaPrincipal/BibliotecaAnime.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="BibliotecaAnime.xsl"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="biblioteca.xsd">
  <anime>
    <Nombre>Naruto</Nombre>
    <Director>Masashi Kishimoto (Creador), Hayato Date, Akira Shimizu, Atsushi Nigorikawa, Atsushi Wakabayashi, Hayato Goda, 
            Hiroshi Kimura, Kazuyoshi Yokota, Kiyomu Fukuda, Masaaki Kumagai, Masahiko Murata, Masayuki Iimura, Mitsutaka Noshitani, 
            Rion Kujo, Shigenori Kageyama, Shinji Satoh, Shuuji Miyahara, Toshiya Niidome, Tsuyoshi Matsumoto, Yuki Hayashi, Yuki Kinoshita
    </Director>
    <Año>2002</Año>
    <Episodios>220 episodios</Episodios>
    <Seiyuu>Junko Takeuchi</Seiyuu>
    <Genero> Serie de TV. Animación. Acción. Fantástico | Ninjas. Artes marciales. Amistad. Manga.</Genero>
    <Sinopsis> La historia transcurre en un mundo dominado por aldeas ninja. En las cuales el papel del ninja se traduce como el poder de 
            cada país. Cada uno de estos cuenta con su aldea oculta que es donde estudian, entrenan, graduan y forman cada ninja. Los ninjas 
            utilizan todo tipo de artes marciales desde la lucha cuerpo a cuerpo a ilusiones o técnicas secretas como por ejemplo la manipulación 
            de elementos.El protagonista es un joven aspirante a ninja Uzumaki Naruto, un muchacho que sueña en convertirse algún día en el líder 
            de su aldea (Hokage). Será para él una tarea difícil ya que cuando era solo un bebé le fué confiado en su interior el poder de un ser 
            malvado, que antaño causó grandes males en su aldea (Konoha) y el cual irá poco a poco descubriendo y dominando. Por culpa de ese poder 
            Naruto pasa una dura infancia con desprecio y negación por parte de los vecinos de su aldea...
    </Sinopsis>
    <Criticas/>
    <Finalizado>Si</Finalizado>
    <Trailer>https://youtube.com/embed/u1lgk_fsDkA</Trailer>
  </anime>
  <anime>
    <Nombre>Mazinger Z</Nombre>
    <Director>Tomoharu Katsumata, Bonjin Nagaki, Katsuhisa Yamada, Kouichi Sasaki, Masamune Ochiai, Masayuki Akehi, Nobuo Onuki, Nobutaka 
            Nishizawa, Takashi Kuoka, Takeshi Tamiya, Tokushige Shirane, Tsunekiyo Otani, Yasuo Yamayoshi, Yoshikatsu Kasai, Yugo Serikawa
    </Director>
    <Año>1972</Año>
    <Episodios>92 episodios</Episodios>
    <Seiyuu/>
    <Genero>Serie de TV. Animación. Acción. Fantástico. Ciencia ficción | Robots. Manga
    </Genero>
    <Sinopsis>Dos arqueólogos encuentran los restos de una civilización antigua que era capaz de construir robots gigantes. Uno de ellos, 
            el doctor Hell (doctor Infierno), cree que si consigue construir unos robots semejantes, entonces podría gobernar al mundo. El 
            otro arqueólogo, el doctor Kabuto, se niega a secundar sus malvados planes y, a partir de ese momento, se convierten en enemigos. 
            Hell ordena que asesinen a Kabuto, pero éste, antes de morir, le había mostrado a su nieto, Koji Kabuto, un robot que había construido 
            en secreto para enfrentarse a Hell. El robot, llamado Mazinger, está construido de la formidable aleación Z. Muerto Kabuto, Koji 
            aprende a pilotar a Mazinger gracias a la ayuda del ayudante de su abuelo, el doctor Yomi, que también ha construido un robot 
            llamado Afrodita A, que será pilotado por su hija Sayaka Yomi. Mazinger Z y Afrodita se enfrentarán entonces a los malvados robots 
            de Hell, con el objetivo de salvar al mundo. 
    </Sinopsis>
    <Criticas/>
    <Finalizado>Si</Finalizado>
    <Trailer>https://www.youtube.com/embed/joEetudPr9s</Trailer>
  </anime>
  <anime>
    <Nombre>Dragon Ball Z</Nombre>
    <Director>Daisuke Nishio</Director>
    <Año>1989</Año>
    <Episodios>291</Episodios>
    <Seiyuu>Nozaka mazawo,Yamadera, Kouichi,Tanaka, Mayumi,Horikawa, Ryo,Furuya, Toru</Seiyuu>
    <Genero>Ciencia ficción. Acción. Aventuras. Fantástico | Artes marciales.</Genero>
    <Sinopsis>En Dragon ball Z Goku se ha convertido en un adulto y está casado con Milk, con la que tiene un hijo llamado Gohan.
            En esta segunda saga de Dragon ball Goku descubrirá que no es un terricola,
            sino que pertenece a una raza de guerreros conocida por ser una de las más poderosas de la galaxia, 
            para posteriormente dar paso a los verdaderos enemigos de la serie.
            Para poder vencer a los nuevos enemigos que irán surgiendo, Goku y sus amigos tendrán que viajar por otros planetas e incluso al cielo y al infierno.
            Cada enemigo será más fuerte que el anterior,
            por lo que tendrán que entrenar muy duro para poder derrotarlos además de que se les irán uniendo nuevos personajes que les ayudarán a vencerlos.
    </Sinopsis>
    <Criticas/>
    <Finalizado>Sí</Finalizado>
    <Trailer>https://www.youtube.com/embed/XGdlAsHgNgY</Trailer>
  </anime>
  <anime>
    <Nombre>Dragon Ball</Nombre>
    <Director>Akira Toriyama (Creador), Daisuke Nishio, Kazuhisa Takenouchi, Minoru Okazaki, Mitsuo Hashimoto, Osamu Kasai, Toshihiko Arisako, Yoshihiro Ueda, Yuji Endo, Yutaka Sato</Director>
    <Año>1986</Año>
    <Episodios>153</Episodios>
    <Seiyuu>Nozaka mazawo,Yamadera, Kouichi,Tanaka, Mayumi,Horikawa, Ryo,Furuya, Toru</Seiyuu>
    <Genero>Ciencia ficción. Acción. Aventuras. Fantástico | Artes marciales</Genero>
    <Sinopsis>Con Goku como protagonista principal de la historia, el argumento se centra en la búsqueda de las legendarias esferas del dragon,
            un total de siete que al ser reunidas daban lugar a la aparición del dragón sagrado que puede conceder cualquier deseo. 
            Goku, con la ayuda de su compañera Bulma además de otros personajes que se irán uniendo con el paso de la historia, 
            se adentrará en la búsqueda de las esferas del dragon y desafiará a todo tipo de villanos para convertirse en el hombre más fuerte del mundo. 
            También se hará especial incapié al Budokai Tenkaichi, un gran Torneo Mundial de Artes Marciales en el que los mejores luchadores de todo el Mundo se darán cita,
            batiéndose en Duelo a fin de demostrar quien es el mas fuerte luchador sobre la Tierra.
    </Sinopsis>
    <Criticas/>
    <Finalizado>Sí</Finalizado>
    <Trailer>https://www.youtube.com/embed/FJqGirLjQn4</Trailer>
  </anime>
  <anime>
    <Nombre>Ranma 1/2</Nombre>
    <Director>Rumiko Takahashi</Director>
    <Año>1989</Año>
    <Episodios>161</Episodios>
    <Seiyuu>Kappei Yamaguchi,Megumi Hayashibara,Kappei Yamaguchi,Megumi Hayashibara</Seiyuu>
    <Genero>Comedia. Romance | Artes marciale</Genero>
    <Sinopsis>¿Cuál es la historia de Ranma 1/2?En Ranma ½ se cuenta la historia de Ranma Saotome,
            quien es un apasionado de las artes marciales y las ha estado practicando desde muy joven junto a su padre.
            En uno de sus entrenamientos, por accidente, 
            tanto él como su padre caen en unos estanques conocidos como estanques encantados de Jusenkyo
    </Sinopsis>
    <Criticas/>
    <Finalizado>Sí</Finalizado>
    <Trailer>https://www.youtube.com/embed/xMJbmdqucfo</Trailer>
  </anime>
  <anime>
    <Nombre>Captain Tsubasa</Nombre>
    <Director>Hiroyoshi Mitsunobu</Director>
    <Año>1983</Año>
    <Episodios>175</Episodios>
    <Seiyuu>Suzumura, Kenichi,Konishi, Katsuyuki,Hatano, Wataru,Tobita, Nobuo</Seiyuu>
    <Genero>Deporte. Fútbo</Genero>
    <Sinopsis>Serie anime basado en el popular manga homónimo creado por Yoichi Takahashi en 1981. La historia comienza cuando Tsubasa Ozora (Oliver), de 12 años de edad, se muda a Shizuoka. 
            El chaval tiene la ilusión de jugar con el equipo más famoso de esa ciudad: el Shutetsu,
            en el cual milita el mejor portero de la liga nacional: Genzo Wakabayashi (Benji). Sin embargo, el protagonista tendrá que entrenar duro y jugar agotadores partidos 
            -incluso lesionado- para alcanzar su sueño: ganar el campeonato nacional de fútbol
    </Sinopsis>
    <Criticas/>
    <Finalizado>si</Finalizado>
    <Trailer>https://www.youtube.com/embed/3zrGjc0UEgU</Trailer>
      </anime>
      <anime>
        <Nombre>Seinto Seiya (Saint Seiya)</Nombre>
        <Director>Kōzō Morishita, Kazuhito Kikuchi</Director>
        <Año>1986</Año>
        <Episodios>114</Episodios>
        <Seiyuu>Hori, Hideyuki,Suzuoki, Hirotaka,Furuya toru,Touma, Yumi</Seiyuu>
        <Genero> Acción. Fantástico | Artes marciales</Genero>
        <Sinopsis>Según cuenta la leyenda, unos jóvenes guerreros poseedores de grandes habilidades son los principales responsables de proteger a Atenea, 
            la diosa de la guerra. Años más tarde, la princesa Saori Kido, reencarnación de la Diosa, se encuentra en peligro y necesita de esa legendaria protección
        </Sinopsis>
        <Criticas/>
        <Finalizado>Sí</Finalizado>
        <Trailer>https://www.youtube.com/embed/BLXHuZ-1C_4</Trailer>
      </anime>
      <anime>
        <Nombre>Legend of galactic heroes</Nombre>
        <Director> Keizo Shimizu, Kenichi Maeda</Director>
        <Año>1992</Año>
        <Episodios>110 </Episodios>
        <Seiyuu/>
        <Genero>Drama. Ciencia ficción | Aventura espacial</Genero>
        <Sinopsis>Ginga Eiyuu Densetsu cuenta la historia de dos bandos, el Imperio Galáctico y la Alianza de Planetas Libres. En el bando del Imperio Galactico se encuentra el Almirante Rheinhardt Von Museal,
            hermano de la protegida del Emperador y en el bando de la Alianza se encuentra el Almirante Yang Wenli. Ambos tienen una visión estratégica impresionante que los lleva a enfrentarse una y otra vez en las batallas. 
            Sin embargo cada uno es repudiado por sus superiores por motivos distintos. La batalla de los Héroes comienza aquí
        </Sinopsis>
        <Criticas/>
        <Finalizado>Si</Finalizado>
        <Trailer>https://www.youtube.com/embed/ReIFoP8T4q8</Trailer>
      </anime>
      <anime>
